- name: Install apache2 web server
  become: true
  apt: pkg={{ item }} state=present update_cache=true
  with_items:
  - apache2
  - libapache2-mod-fcgid

- name: Enable apache2 modules
  become: yes
  command: a2enmod rewrite actions fcgid alias proxy_fcgi

- name: Upload apache2 default configuration
  become: yes
  copy: src=files/000-default.conf dest=/etc/apache2/sites-enabled/

- name: Restart webserver
  become: yes
  service: name=apache2 state=restarted